In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'C:\Users\t2262867\Documents\References\Past_projects\Education\sample_data.csv')

In [3]:
data

       Unnamed: 0    TERM STUDENT_ID     COURSE CAMPUS GRADE
0               0  2021FL    zpomxyc  ENGL-1301     SE     B
1               1  2021FL    npfrrgi  ENGL-1301     NE     F
2               2  2021FL    fzapltz  ENGL-1301     SO     B
3               3  2021FL    xvvdykp  ENGL-1301     NW    CR
4               4  2021FL    zkgjyqz  ENGL-1301     SO     D
...           ...     ...        ...        ...    ...   ...
24995       24995  2023FL    itcbpfh  ENGL-1301     TR     F
24996       24996  2023FL    yxzklon  ENGL-1301     SE     A
24997       24997  2023FL    mvjolaa  ENGL-1301     SO     B
24998       24998  2023FL    lqmsszq  ENGL-1301     SO     B
24999       24999  2023FL    awpupqc  ENGL-1301     SO     F

[25000 rows x 6 columns]